from PyInstaller.utils.hooks import collect_submodules
hiddenimports = [
    'django.contrib.admin.apps',
    'django.contrib.auth.apps',
    'django.contrib.contenttypes.apps',
    'django.contrib.sessions.apps',
    'django.contrib.messages.apps',
    'django.contrib.staticfiles',
    'django.contrib.staticfiles.apps',
    'django_extensions',
    'base.urls',
    'usuario.urls',
    'vivienda.urls',
    'vivienda.grupo_familiar.urls',
    'vivienda.grupo_familiar.persona.urls',
    'reporte.urls',
    'django.contrib.messages.middleware',
    'django.contrib.auth.middleware',
    'django.contrib.sessions.middleware',
    'django.contrib.sessions.serializers',
    'django.template.loaders',
    'django.contrib.auth.context_processors',
    'django.contrib.messages.context_processors',
]
